<h1 id="types_objects" align="center">Practice with NumPy</h1>

**If you have never studied linear algebra** you may find this notebook to be overly difficult. Let me know if that´s the case while we are in the lab. Linear algebra is at the basis of data science and machine learning, which makes extensive use of matrix formalism. However, Python is solving all linear algebra problems for you.

Fill in the missing code in the exercises and submit this notebook as part of your Assignment 3.<br>
Go as far down the list as you can.

This is a collection of exercises that have been gathered online and in the NumPy documentation. These are meant to be solved on your own during the lab or at home.<br>

Each exercise is tagged with stars, showing the level of challenge.<br>
 (★☆☆) easy<br>
 (★★☆) medium difficulty<br>
 (★★★) advanced <br>
 
If you encouter difficulties, check my notebooks. <br>
If you still encounter difficulties, check the online documentation.<br>


### N.B.: the following exercises are also meant for you to familiarise with functions and operations that have not been introduced in class
#### Please refer to the NumPy official documentation to find out how to solve as many cases as you can.
https://docs.scipy.org/doc/numpy/

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.version.version

'1.17.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [7]:
import sys
sys.getsizeof(x)

176

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
z = np.array(range(10, 50))
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
np.flip(z)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
a = np.arange(9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [23]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
np.random.rand(3, 3, 3)

array([[[6.55097259e-01, 8.14146107e-01, 7.18059748e-01],
        [9.29594168e-01, 5.63910940e-01, 5.13143262e-01],
        [2.50860623e-01, 3.96334355e-01, 7.88927210e-01]],

       [[2.63535620e-02, 2.34084133e-04, 2.39658840e-01],
        [5.59998847e-01, 7.46891345e-01, 9.32815529e-01],
        [6.64181815e-01, 7.76703699e-01, 1.83932696e-01]],

       [[3.92473605e-01, 7.11325439e-02, 6.25766149e-01],
        [5.67340598e-01, 7.10783538e-01, 4.88572833e-01],
        [9.74258580e-01, 1.15268963e-01, 6.11380181e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
ten = np.random.rand(10, 10)
print(ten)

print(np.min(ten))
print(np.max(ten))

[[0.55086579 0.90417998 0.95935926 0.78669081 0.49810031 0.49425372
  0.16478554 0.93332802 0.89961556 0.85353413]
 [0.15114288 0.61964125 0.25928257 0.42251288 0.70382046 0.81691794
  0.37400702 0.0303236  0.33286477 0.68097846]
 [0.66018133 0.65273736 0.2657219  0.08920669 0.74220717 0.01795081
  0.02260879 0.08118661 0.60213229 0.43841009]
 [0.55685763 0.51319395 0.60790295 0.31572086 0.64442127 0.63596689
  0.39357011 0.68756055 0.88425624 0.54568687]
 [0.64332078 0.29211202 0.99336605 0.38081805 0.45337409 0.44250996
  0.99556536 0.33581252 0.27401692 0.09415125]
 [0.14052933 0.88937517 0.09987342 0.11990798 0.38720522 0.50301125
  0.78430199 0.83137023 0.06499418 0.77240834]
 [0.94382147 0.26104163 0.75638113 0.89183717 0.08103323 0.33931979
  0.38803446 0.20745277 0.13393864 0.94650839]
 [0.21309308 0.76938079 0.42921455 0.09549242 0.72387356 0.03820136
  0.5101414  0.02468474 0.82799739 0.84916937]
 [0.35670335 0.87017748 0.67098792 0.57815756 0.63086608 0.51616766
  0.46520464

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
np.mean(np.random.rand(30))

0.4078733804931749

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
border = np.ones((5,5))
border[1:-1,1:-1] = 0
border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [53]:
another_border = np.zeros((5,5))
np.pad(another_border, pad_width=1, mode='constant', constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [54]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [59]:
np.indices([8,8]).sum(axis=0) % 2


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [61]:
np.dot(np.random.rand(5, 3), np.random.rand(3, 2))

array([[0.69408622, 0.37072664],
       [0.57076265, 0.70238929],
       [0.95116249, 1.2258453 ],
       [0.84035664, 0.89498872],
       [0.90926808, 0.48582362]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [63]:
arr = np.array(range(-5, 100))

m = (arr > 2) & (arr < 9)
arr[m] *= -1

arr

array([-5, -4, -3, -2, -1,  0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [66]:
print(np.arange('2012-07', '2020-08', dtype='datetime64[D]'))

['2012-07-01' '2012-07-02' '2012-07-03' ... '2020-07-29' '2020-07-30'
 '2020-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) ? (★★☆)

In [72]:
A = np.array([[1, 4], [5,2]])
B = np.array([[11, 2], [3,3]])

np.dot((A + B),((-A)/2))

array([[-21. , -30. ],
       [-16.5, -21. ]])

#### 36. Extract the integer part of a random array (★☆☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [76]:
np.zeros(25).reshape((5, 5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [82]:
np.arange(0.05, 1, 0.1)

array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [89]:
np.sort(np.random.rand(10))


array([0.18885528, 0.25581667, 0.26849197, 0.3413642 , 0.62666067,
       0.66533026, 0.67686378, 0.77211622, 0.7967227 , 0.9149979 ])

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [92]:
sum(np.random.rand(10) == np.random.rand(10)) != 0

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [101]:
r = np.random.rand(10)
print(r)
r[np.where(r == np.max(r))] = 0

print(r)

[0.26476329 0.96807674 0.35853313 0.69044192 0.4659545  0.93790047
 0.51825833 0.75117063 0.57793933 0.490044  ]
[0.26476329 0.         0.35853313 0.69044192 0.4659545  0.93790047
 0.51825833 0.75117063 0.57793933 0.490044  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [107]:
vec = np.random.rand(100)
print(vec)
sc = 0.5

np.where((vec - sc) == np.min(np.absolute(vec - sc)))

[0.62302626 0.38327416 0.53982184 0.65768406 0.36636175 0.22967703
 0.15860665 0.40974876 0.15371136 0.61162321 0.72438084 0.38473097
 0.93564673 0.02091479 0.0807816  0.3707608  0.61846089 0.75567209
 0.65092834 0.14010243 0.70148859 0.02903284 0.84642613 0.69163994
 0.39436938 0.66386789 0.05491597 0.7334135  0.11391402 0.77370121
 0.37860265 0.48651979 0.8517513  0.67849608 0.00907183 0.87615134
 0.55598374 0.86441992 0.00438967 0.26396827 0.0506441  0.44735678
 0.20192374 0.02262037 0.58798324 0.50787617 0.23002707 0.75891294
 0.93678227 0.92684344 0.88234498 0.05961602 0.16405306 0.71287478
 0.73703083 0.14539744 0.09796111 0.84518745 0.52216218 0.50297644
 0.5825092  0.10119999 0.88025771 0.07571383 0.0990901  0.45187339
 0.5833035  0.04905256 0.71198638 0.89254287 0.14805695 0.53296321
 0.12179448 0.04539764 0.2151689  0.92781356 0.6819699  0.93270162
 0.965006   0.87205332 0.93196198 0.47165733 0.08854319 0.2956852
 0.37422419 0.10385985 0.89423851 0.20323863 0.44692476 0.50427

(array([59], dtype=int64),)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [110]:
print(np.ndenumerate(np.array([[1, 2], [3, 4]])))

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [12]:
import math
p = 100
n = int(math.sqrt(p))

np.random.rand(p).reshape((n, n))

array([[0.82724124, 0.71418722, 0.41729878, 0.06201532, 0.36040472,
        0.66428886, 0.31191372, 0.24123889, 0.87441737, 0.5619632 ],
       [0.9683866 , 0.72474592, 0.53359939, 0.02218721, 0.96975736,
        0.38450273, 0.23120572, 0.32890818, 0.57200828, 0.93749197],
       [0.72964114, 0.48967895, 0.91025724, 0.42879711, 0.44333532,
        0.24909992, 0.02021468, 0.15497778, 0.30336033, 0.84407581],
       [0.94951077, 0.34315818, 0.22120532, 0.94135809, 0.32720651,
        0.06797173, 0.98183619, 0.5672012 , 0.16420241, 0.81727552],
       [0.71203818, 0.80896117, 0.27901941, 0.19036706, 0.43552571,
        0.99819016, 0.71524895, 0.48315463, 0.88001954, 0.72032513],
       [0.96194989, 0.88288463, 0.92515002, 0.43620199, 0.97901395,
        0.26491697, 0.88099468, 0.448707  , 0.33923161, 0.9432559 ],
       [0.45385653, 0.76980246, 0.98498729, 0.46062752, 0.10596243,
        0.31551145, 0.45378852, 0.65541215, 0.35436706, 0.34590005],
       [0.56433465, 0.95280515, 0.3216286

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [14]:
arr = np.random.rand(p).reshape((n, n))

arr - np.mean(arr, axis = 0)


array([[ 0.04615784, -0.36240968, -0.49303614,  0.01201568,  0.42545831,
        -0.22916865,  0.39028596, -0.10102561, -0.59331389,  0.03685236],
       [ 0.13665307,  0.07474381,  0.01262227, -0.27206121,  0.22712673,
         0.1238291 ,  0.04939494, -0.14004667,  0.14158156, -0.02311693],
       [-0.49858099,  0.04591405,  0.11294631,  0.20622608, -0.46387847,
        -0.47792376, -0.17226507,  0.37619278,  0.21949519,  0.36568196],
       [-0.0440274 , -0.15988907, -0.19569768, -0.17865501,  0.02399877,
        -0.41972786, -0.15991505,  0.09740133, -0.0243605 ,  0.26742139],
       [ 0.14217276,  0.17952639, -0.38294948,  0.18252784, -0.2785352 ,
         0.34957821,  0.24974685,  0.06719244,  0.08437458, -0.48793053],
       [ 0.22439388, -0.15990083,  0.10254984,  0.20502796, -0.4088395 ,
         0.17622015, -0.38372288,  0.29669657,  0.00419161, -0.00723514],
       [ 0.27304475, -0.20116482,  0.32705517,  0.14532968,  0.23355545,
        -0.01230605,  0.16985441, -0.30139438

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [40]:
nc = np.random.randint(0,2,(3,3))


sum(np.sum(nc, axis = 1) == 0) > 0



True

#### 69. How to get the diagonal of a dot product? (★★★)

In [42]:
A = np.random.randint(0, 100,(4,4))
B = np.random.randint(0, 100,(4,4))

np.diag(np.dot(A, B))

array([8572, 8757, 5447, 2392])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [63]:
vector = [1, 2, 3, 4, 5]

np.ndarray.flatten(np.array([np.array((vector[o-1], 0,0,0)) for o in vector]))
    

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

#### 89. How to get the n largest values of an array (★★★)

In [74]:
n = 5

np.sort(np.random.randint(0,100, 100))[-n-1:-1]

array([93, 93, 93, 95, 98])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [109]:
mat = np.random.randint(0,3, (10,3))
print(np.shape(mat))
print(mat)
print((mat[:, 0] - mat[:, 1] == 0) * (mat[:, 1] - mat[:, 2] == 0) == 1)

mat[(mat[:, 0] - mat[:, 1] == 0) * (mat[:, 1] - mat[:, 2] == 0) == 1, :]

(10, 3)
[[0 1 0]
 [1 0 1]
 [0 1 2]
 [0 2 0]
 [2 2 1]
 [1 0 0]
 [2 2 2]
 [1 2 1]
 [1 2 1]
 [0 1 0]]
[False False False False False False  True False False False]


array([[2, 2, 2]])