# Self-learning Notebook
Go through all the examples included in this notebook, to familiarize with the routines.<br>
These examples are typical in many data science workflows. Make sure you fully understand how the routines work and keep them at hand for when you´ll need them.<br>
This is a self-learning notebook. There is no need to submit it or prove that you have completed it. It´s for your own benefit and will make your life easier for the bigger project assignment due in January.

# Random Sampling

In [1]:
import numpy as np

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [2]:
np.random.rand(3,2)
# array([[ 0.13879034,  0.71300174],
#        [ 0.08121322,  0.00393554],
#        [ 0.02349471,  0.56677474]])

array([[0.90073514, 0.54038244],
       [0.0140539 , 0.74323549],
       [0.2587947 , 0.86786156]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [3]:
x = np.random.standard_normal(size=(1000,1000))
print(np.mean(x))
print(np.std(x))

0.0016491944498885258
1.000044275503823


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [4]:
np.random.randint(0,4,size=(3,2))

array([[0, 0],
       [1, 2],
       [0, 2]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [5]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']
for i in range(10):
    print(np.random.choice(x,p=[0.3, 0.5,0.2]))

b'2 out of 10'
b'5 out of 10'
b'5 out of 10'
b'3 out of 10'
b'5 out of 10'
b'3 out of 10'
b'5 out of 10'
b'3 out of 10'
b'3 out of 10'
b'5 out of 10'


## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [6]:
x = np.arange(10)
np.random.shuffle(x)
print(x)


[8 3 0 2 7 5 6 9 1 4]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [7]:
np.random.seed(10)
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

Q8. Now see what happens if no seed has been set. Each time you re-run the cell, you´ll get different results

In [8]:
np.random.rand(3)

array([0.74880388, 0.49850701, 0.22479665])